name: Release to docker
on: 
  push: 
    branches: ['main']

jobs: 
  get_version:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ env.PACKAGE_VERSION }}
    steps: 
      - name: Set Calver Version 
        uses: Nelyx/action-calver@v1.1.0
        with: 
          default_branch: 'refs/heads/main'
          format: 'YYYYMMDD'
          version_prefix: ''

      - name: Current verion 
        run: 'echo Version: ${{ env.PACKAGE_VERSION }}'

  deploy: 
    runs-on: ubuntu-latest
    needs: get_version
    steps: 
      - name: Copy Repo Files
        uses: actions/checkout@master

      - name: Set up QEMU 
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: Dockerfile
          pull: true
          push: true
          tags: nyffelsit/github-runner:latest,nyffelsit/github-runner:${{ needs.get_version.outputs.version }}